CREATE TABLE bought_tickets(
    ticket_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    departure VARCHAR(50),
    arrival VARCHAR(50),
    segments INT,
    price DECIMAL,
    currency VARCHAR(3),
    traveller VARCHAR(100),
    traveller_amount DECIMAL
);

CREATE TABLE users(
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR NOT NULL
);